### ISSUE TITLE
fix lintian errors

### ISSUE THREAD

**Issue by berndpfrommer** [borglab/gtsam-packaging#8]
Currently the debian packaging scripts (gbp) produce a bunch of lintian errors, see #1 
These need to be fixed.

**Comment by jlblancoc** [comment]
Looking closer at the lintian errors/warnings, the only relevant one are: 

```
W: libgtsam4: dev-pkg-without-shlib-symlink usr/lib/x86_64-linux-gnu/libmetis-gtsam.so usr/lib/x86_64-linux-gnu/libmetis-gtsam.so
W: libgtsam4: shlib-without-versioned-soname usr/lib/x86_64-linux-gnu/libmetis-gtsam.so libmetis-gtsam.so
```

But libmetis-gtsam is actually there "temporarily", since we should use the system versions, so... all is better than it looked at first sight!

The other ITP bug warning means we should someday declare the intention to package GTSAM in front of the Debian community by opening an ITP bug, just in case someone has something to say.  Then, the first time the package is uploaded to mentors.debian.org and get sponsored by someone, the bug will be marked as closed.

**Comment by jlblancoc** [comment]
PS: Further clarification: Fixing https://github.com/borglab/gtsam/issues/292 will fix this one too, that's why I closed it.
